Un booléen est une valeur qui est vrai ou fausse (probablement vu dans le cadre conditions (`if`)

In [1]:
True #vrai

True

In [2]:
False # Faux

False

On peut les comparer

In [3]:
True == True

True

In [4]:
True == False

False

In [5]:
False == False

True

On peut comparer d'autres objets, et la comparaison va retourner un booléen.

In [6]:
3 == 3

True

In [7]:
a = 3
b = 2

In [8]:
a != a

False

In [9]:
a > b

True

In [10]:
a > a

False

In [11]:
a >= a

True

Opérateur booléen
[doc officielle](https://docs.python.org/3/reference/expressions.html#boolean-operations)  
[Doc sur l'ensembles des opérateurs en python](https://www.datacamp.com/community/tutorials/python-operators-tutorial?utm_source=adwords_ppc&utm_campaignid=898687156&utm_adgroupid=48947256715&utm_device=c&utm_keyword=&utm_matchtype=b&utm_network=g&utm_adpostion=&utm_creative=332602034352&utm_targetid=aud-522010995285:dsa-429603003980&utm_loc_interest_ms=&utm_loc_physical_ms=1006356&gclid=CjwKCAjw7J6EBhBDEiwA5UUM2rhDBU74gk9hf-polD-cR7mMcESkG3BVcoqhm3OtMOybovSL6cHqOxoCW0AQAvD_BwE)

In [12]:
(3 == 3) and (3==2)

False

In [13]:
(3 == 3) or (3==2)

True

In [14]:
 (3 == 3) or (not(3==2))

True

In [15]:
 (3 == 3) and (not(3==2))

True

En data science on utilise souvent les équivalents en Bitwise `&`, `|`, `~`  (plus rarement `^` (exclusive or -- xor) et encore plus rarement (jamais?) `<<` `>>` bitwise left and right shift operator ), car il permettent de faire une comparaison élément par élément au sein d'un vecteur.

- & correcpond au **and**
- | correspond au **or**
- ~ correspond au **not**

In [16]:
import numpy as np
np.array([True,True, False, True]) and np.array([True,False, False, True])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [17]:
import numpy as np
np.array([True,True, False, True]) & np.array([True,False, False, True])

array([ True, False, False,  True])

In [18]:
import numpy as np
np.array([True,True, False, True]) | np.array([True,False, False, True])

array([ True,  True, False,  True])

In [19]:
import numpy as np
np.array([True,True, False, True]) | (~np.array([True,False, False, True]))

array([ True,  True,  True,  True])

In [20]:
import numpy as np
np.array([True,True, False, True]) & (~np.array([True,False, False, True]))

array([False,  True, False, False])

In [21]:
(~np.array([True,False, False, True]))

array([False,  True,  True, False])